name: damath
description: math collection for dart.
version: 0.0.46
repository: https://github.com/nomagicisreal/damath

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  flags_binary: ^0.0.2
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0